### ISSUE TITLE
Unused vars

### ISSUE THREAD

**Issue by jbrooksuk** [convergame/convergame-engine#12]
The following `hasGp`, `regGP`, `axes` (`axis?`) are unused.

**Comment by DivineOmega** [comment]
These are probably remnants of when the game engine was very closely tied into the sample game you saw at Staffs Web Meetup. Can you confirm this @ojdon?

**Comment by ojdon** [comment]
It's from the Gamepad API Integration that we removed due to needing space for our js13k entry. As we have only worked from master, it has been removed.

I'm closing this for now as it'll be eventually rewritten once we have knuckled down the foundation of the new input management functionality for handling stuff like Gamepad APIs, etc.
